# SPDX-FileCopyrightText: 2024 Mehver (https://github.com/Mehver)
# SPDX-License-Identifier: BSD-3-Clause
version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/app/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/app/backend/requirements"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    
