name: Build and Release

on:
  release:
    types: [created]  # 当创建新的 Release 时触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - uses: actions/checkout@v2  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'  # 设置 Python 版本

    - name: Set Compile Environment
      run: .\bin\packaging\win-resetenv.bat  # 运行环境重置脚本

    - name: Build Project
      run: .\bin\packaging\win-onefile.bat  # 运行构建脚本

    - name: Rename and Prepare for Upload
      run: |
        $newName = "icontroller-${{ github.event.release.tag_name }}-portable-win-x64.exe"
        Rename-Item .\dist\main.exe $newName
        echo "ARTIFACT_PATH=.\dist\$newName" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}  # Release 的上传URL
        asset_path: ${{ env.ARTIFACT_PATH }}
        asset_name: ${{ env.ARTIFACT_PATH }}
        asset_content_type: application/octet-stream
